### ISSUE TITLE
Scene view displays 500 error

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-concierge#1]
### Issue:
Migrated 2 scenes from Play #227471 - Gunboat Philadelphia and #7028463 - Qing Dynasty Porcelain Dish but was not able to view the scene in Voyager. Once migration completed, assets in scene bins were viewable in Concierge asset tab, but trying to access the scenes via a popcorn icon or the Scene button in the left hand navigation pane returns an 

 `Query Error
Network error: Response not successful: Received status code 500`

### Actions to reproduce:
Use migration tool to migrate Play scene, once scene is migrated try to view scene in voyager

### Notes:
Scene assets for #7028463 - Qing Dynasty Porcelain Dish looked correct, scene bin contained glb and scene.svx.json
Scene assets for #227471 - Gunboat Philadelphia did not look correct, scene bin only contained article html pages and article images

![image](https://user-images.githubusercontent.com/49207360/69369804-ae62d200-0c6a-11ea-8f2c-cf2672563bed.png)

**Comment by framefactory** [comment]
Can't reproduce. I can access both scenes, they open in both Voyager Explorer and Voyager Story.
Possible solution: clear your browser cache, then log in again.

**Comment by framefactory** [comment]
![image](https://user-images.githubusercontent.com/550450/69417530-25ef3a80-0d19-11ea-88a9-19ed3e8bc6cd.png)

**Comment by blundellj** [comment]
Clearing the browser cache worked! Thanks!
